# Author: Jintao Zhang <zhangjintao9020@gmail.com>
image: taobeier/docker

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_PATH

stages:
  - test
  - build

test:
  image: node:10.13
  stage: test
  script:
    - npm install
    - npm test

build:
  stage: build
  script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker build --build-arg NODE_ENV=production -t $IMAGE_NAME:$CI_COMMIT_REF_NAME .
    - docker images
    - docker push $IMAGE_NAME:$CI_COMMIT_REF_NAME
    - docker logout $CI_REGISTRY
